// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using HealthCondition within kubernetes types, where deepcopy-gen is used.
func (in *HealthCondition) DeepCopyInto(out *HealthCondition) {
	p := proto.Clone(in).(*HealthCondition)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCondition. Required by controller-gen.
func (in *HealthCondition) DeepCopy() *HealthCondition {
	if in == nil {
		return nil
	}
	out := new(HealthCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HealthCondition. Required by controller-gen.
func (in *HealthCondition) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using HealthConditionedStatus within kubernetes types, where deepcopy-gen is used.
func (in *HealthConditionedStatus) DeepCopyInto(out *HealthConditionedStatus) {
	p := proto.Clone(in).(*HealthConditionedStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthConditionedStatus. Required by controller-gen.
func (in *HealthConditionedStatus) DeepCopy() *HealthConditionedStatus {
	if in == nil {
		return nil
	}
	out := new(HealthConditionedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HealthConditionedStatus. Required by controller-gen.
func (in *HealthConditionedStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
