// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using Lifecycle within kubernetes types, where deepcopy-gen is used.
func (in *Lifecycle) DeepCopyInto(out *Lifecycle) {
	p := proto.Clone(in).(*Lifecycle)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lifecycle. Required by controller-gen.
func (in *Lifecycle) DeepCopy() *Lifecycle {
	if in == nil {
		return nil
	}
	out := new(Lifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Lifecycle. Required by controller-gen.
func (in *Lifecycle) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
