// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using Reference within kubernetes types, where deepcopy-gen is used.
func (in *Reference) DeepCopyInto(out *Reference) {
	p := proto.Clone(in).(*Reference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference. Required by controller-gen.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Reference. Required by controller-gen.
func (in *Reference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TypedReference within kubernetes types, where deepcopy-gen is used.
func (in *TypedReference) DeepCopyInto(out *TypedReference) {
	p := proto.Clone(in).(*TypedReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedReference. Required by controller-gen.
func (in *TypedReference) DeepCopy() *TypedReference {
	if in == nil {
		return nil
	}
	out := new(TypedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TypedReference. Required by controller-gen.
func (in *TypedReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Selector within kubernetes types, where deepcopy-gen is used.
func (in *Selector) DeepCopyInto(out *Selector) {
	p := proto.Clone(in).(*Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector. Required by controller-gen.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Selector. Required by controller-gen.
func (in *Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceSpec within kubernetes types, where deepcopy-gen is used.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	p := proto.Clone(in).(*ResourceSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec. Required by controller-gen.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec. Required by controller-gen.
func (in *ResourceSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceStatus within kubernetes types, where deepcopy-gen is used.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	p := proto.Clone(in).(*ResourceStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus. Required by controller-gen.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus. Required by controller-gen.
func (in *ResourceStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceName within kubernetes types, where deepcopy-gen is used.
func (in *ResourceName) DeepCopyInto(out *ResourceName) {
	p := proto.Clone(in).(*ResourceName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceName. Required by controller-gen.
func (in *ResourceName) DeepCopy() *ResourceName {
	if in == nil {
		return nil
	}
	out := new(ResourceName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceName. Required by controller-gen.
func (in *ResourceName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TargetStatus within kubernetes types, where deepcopy-gen is used.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	p := proto.Clone(in).(*TargetStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus. Required by controller-gen.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus. Required by controller-gen.
func (in *TargetStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TargetUsage within kubernetes types, where deepcopy-gen is used.
func (in *TargetUsage) DeepCopyInto(out *TargetUsage) {
	p := proto.Clone(in).(*TargetUsage)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetUsage. Required by controller-gen.
func (in *TargetUsage) DeepCopy() *TargetUsage {
	if in == nil {
		return nil
	}
	out := new(TargetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TargetUsage. Required by controller-gen.
func (in *TargetUsage) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
